name: treechan
description: Browser for imageboard.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.14.0

environment:
  # sdk: '>=2.18.6 <=3.1.0'
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_html: ^2.2.1
  html: ^0.15.4
  swipe_image_gallery: ^0.8.0
  shared_preferences: ^2.0.17
  flexible_tree_view:
    git:
      url: https://github.com/radibobovich/flexible_tree_view.git
  grouped_list: ^5.1.2
  url_launcher: ^6.1.8
  easy_refresh: ^3.3.2+1
  visibility_detector: ^0.3.3
  args: ^2.4.0
  photo_view: ^0.14.0
  flick_video_player: ^0.5.0
  video_player: ^2.5.2
  flutter_bloc: ^8.1.2
  settings_ui: ^2.0.2
  sqflite: ^2.2.6
  path: ^1.8.2
  intl: ^0.17.0
  sqflite_common_ffi: ^2.2.3
  sqlite3_flutter_libs: ^0.5.13
  share: ^2.0.4
  provider: ^6.0.5
  pausable_timer: ^1.0.0+7
  test: ^1.22.0
  noob: ^0.0.8
  should_rebuild: ^1.0.1
  extended_image: ^8.1.0
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.0.1
  flutter_local_notifications: ^15.1.1
  mockito: ^5.4.2
  injectable: ^2.3.0
  get_it: ^7.6.4
  gallery_saver_updated:
    git:
      url: https://github.com/ARTISAN-inc/gallery_saver_updated.git
  image_gallery_saver: ^2.0.3
  dio: ^5.3.3
  flutter_svg: ^2.0.7
  flutter_fgbg: ^0.3.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  hidable:
    git: 
      url: https://github.com/insolite-dev/hidable
      ref: develop
  floor: ^1.4.2
  flutter_form_builder: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
    
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  floor_generator: ^1.4.2

dependency_overrides:
  flutter_layout_grid: ^2.0.4
  flutter_math_fork: ^0.7.0
  flutter_svg: ^1.0.0
  path_drawing: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/test/
    - assets/dev/

    - assets/icons/browsers/
    - assets/icons/os/